[project]
name = "fplysis"
version = "0.1.0"
description = "Monitor FPL performance and get transfer suggestions."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "fpl>=0.6.35",
    "isort>=6.0.1",
    "tqdm>=4.67.1",
]
