name: black

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - run: pip install black
      - run: black .
      - uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: black code format run
