name: code-format

on: [push, pull_request]

jobs:
  run-isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v6
      - run: uv python install
      - run: uv sync
      - run: uv run isort --skip hacks --skip .venv .
      - uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: isort code format run

  run-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v6
      - run: uv python install
      - run: uv sync
      - run: uv run black --exclude "/(hacks|.venv)/" .
      - uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: black code format run
