name: code-format

on: [push, pull_request]

jobs:
  run-isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: python -m pip install poetry
      - run: poetry install
      - run: poetry run isort .
      - uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: isort code format run

  run-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: python -m pip install poetry
      - run: poetry install
      - run: poetry run black .
      - uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: black code format run
