name: pytest

on: [push, pull_request]

jobs:
  run-poetry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: astral-sh/setup-uv@v6
      - run: uv python install
      - run: uv sync
      - run: ./hacks/hacks.sh
      - run: uv run pytest
