name: pytest

on: [push, pull_request]

jobs:
  run-poetry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - uses: snok/install-poetry@v1
      - run: poetry install
      - run: poetry run pytest
